### ISSUE TITLE
404 page color error in dark mode

### ISSUE THREAD

**Issue by dengnao-tw** [guangzhengli/hugo-theme-ladder#22]
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/85914991/233604710-27df4724-0247-48c3-bb3b-964ad4f94823.png">

**Comment by guangzhengli** [comment]
Fix it.

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/39078991/233623719-95dd3fdf-1e21-43c8-9113-280747ab51c9.png">
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/39078991/233623755-fcd6c184-ef60-442d-9069-4922d2d80b38.png">
